CC = /opt/host/armv4l/bin/armv4l-unknown-linux-gcc

LD = /opt/host/armv4l/bin/armv4l-unknown-linux-ld

CFLAGS = -D__KERNEL__ -I/lzj/kernel/include -Wall -Wstrict-prototypes -Wno-trigraphs -Os -mapcs -fno-strict-aliasing -fno-common -fno-common -pipe -mapcs-32 -march=armv4 -mtune=arm9tdmi -mshort-load-bytes -msoft-float -DKBUILD_BASENAME=Lcd_driver -I/opt/host/armv4l/src/linux/include -DMODULE
      
Lcd_driver.o: Lcd_driver.c
	$(CC) $(CFLAGS) -c $^ -o $@
	cp Lcd_driver.o /home/nfs
clean:
	-rm  *.o
